#!/bin/sh


# Bordes redondeados (requiere bspwm-rounded)
bspc config border_radius 12
bspc config border_width 2
bspc config focused_border_color "#ff70a6"
bspc config normal_border_color "#222222"


# Gaps
aint=8
bspc config window_gap $aint
bspc config top_padding 40


# Layout
aint=1
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true


# Wallpaper
feh --bg-fill ~/.config/wallpaper/wall.png


# Polybar
pkill polybar
polybar main &


# Widgets
lxterminal -e fastfetch &
lxterminal -e "unimatrix -a -c green" &
lxterminal -e "tty-clock -c -C 2" &
 
